version: "3"

services:
  my-jenkins:
    build: .
    ports:
      - "11001:5000"
      - "11002:5000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock